spring.application.name=smart-api-gateway

server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.gateway.server.webflux.routes[0].id=shipment-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://SMART-SHIPMENT
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/shipments/**

spring.cloud.gateway.server.webflux.routes[1].id=notification-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://SMART-NOTIFICATION
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/notifications/**
